### PR TITLE
Patch 5

### PR DESCRIPTION
**Pull request by lonevvolf**

### CODE REVIEW

**Comment by cracrayol** [comment]
Why don't you just put <meal /> instead of <meal huntDisabled="true" /> ?

The meal tag will give the choice of choosing huntmastery (and text say that the player is "able", it dosen't force the player to use it).

**Comment by lonevvolf** [comment]
Does the tag take into account the Hunting doesn't count, but Huntmastery does?

**Comment by cracrayol** [comment]
Ah yes, i've forgot this subtlety between hunting and huntmastery (hunting only for fertile areas). It's ok, then.

**Comment by lonevvolf** [comment]
Actually, I just tested, and it looks like it works as it should.  I will correct it, thanks

**Comment by cracrayol** [comment]
After testing, your first correction was the good one (if you have only kai hunting discipline, your can't user hunt in those sections).

**Pull request closed without merging**
