### PR TITLE
Fix for book6section284

### PR DESCRIPTION
**Pull request by lonevvolf**
Betting section was also hit with linter fixes - all tests now passing.

@cracrayol I wonder if we can add the execution of the test suite to the GitHub Actions workflow.  Might be worth it to have a working suite.

### CODE REVIEW

**Comment by cracrayol** [comment]
Could be a good idea. I'm trying to setup the tests to use the headless version of chrome.

**Comment by cracrayol** [comment]
The only drawback is that running test for all books will take a lot of time, mainly due to the playbook test that test every sections of every book, and each section is tested about the rendering, the combats (playing or eluding), the random table and the meal.

For 22 books, it's about ~40000 tests executed.

**Comment by lonevvolf** [comment]
Yes, I've seen that - the other concern is not just the time taken, but limits on the free GitHub Pages (or other runner):

> "GitHub Pages deployments will timeout if they take longer than 10 minutes."
Perhaps we can limit it to the base tests, and we can allow manual execution of the book tests with a parameter for a single book.  Even though this takes a while, it should stay under 10 minutes, and allows to run targeted testing on a book being developed or having an issue.

**Comment by cracrayol** [comment]
I've implemented an automatic start/stop of webpack dev server when running the tests.
I've also added the tests execution to github actions. For the playbook part, it only check the tssf section of book 1.

**Pull request merged**
